# +----------------------------------------------------+
# <               AdvancedKits Reloaded                >
# <                 Configuration file                 >
# <                     config.yml                     >
# +----------------------------------------------------+
# You can enable the economy hook via Vault
# You need an Economy plugin, like Essentials
use-economy: true
# If this option is true, the player who buys a kit will automatically use it.
use-on-buy: false
# You can change the chat prefix.
# So it's looks more unique :)
chat-prefix: '&7[&6AdvancedKits&7]'
# AdvancedKitsReloaded support multilanguage.
# Currently there are the available values:
# English: en | Hungarian: hu | Portoguese: pt | Italian: it | Finnish: fi | French: fr
# If you'd like to translate it here:
# https://ackuna.com/translate-/advancedkits-reloaded/
locale: en