on-create:
  protection: true
  monster: false
  animal: false
  welcome: false
  farewell: false
  heal: false
  hurt: false
  pvp: false
  creeper: false
  tnt: false
  explosion: false
  fire: false
  restriction: false
  jail: false
  lightning: false
  deathdrop: false
  safedeath: false
  drop: false
  interact: true
  enderman: false
  god: false
  gamemode: false
  fly: false
  takeitem_in: false
  takeitem_out: false
  giveitem_in: false
  giveitem_out: false
  melt: false
  teleport: false
  water_flow: false
  lava_flow: false
locale: en
listeners:
  healthListener: true
tools:
  check: WOOD_SWORD
  define: WOOD_SPADE
particles:
  enabled: false
  particle: FIREWORKS_SPARK
healing:
  time: 3
  amount: 1
hurting:
  time: 7
  amount: 2
restriction:
  size:
    (-1, -1, -1): izone.zone.max-size.unlimited
    (50, 256, 50): izone.zone.max-size.1
  zone:
    '-1': izone.zone.max-zone.unlimited
    '3': izone.zone.max-zone.1